name: Deploy Backend
on:
  push:
    branches: [main]
    paths:
      - backendcloud/backend/**

jobs:
  deploy: Deployment
  runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
